### ISSUE TITLE
Azure Open AI Service setting not working.

### ISSUE THREAD

**Issue by kierunb** [chatgptui/desktop#14]
I checked and tested configuration settings for Azure OpenAI Service using two different pairs of endpoints, API keys and models. 

I'm getting two different type of errors, though (for 'gpt-4' and 'gpt-3.5-turbo' models, respectively).

![image](https://github.com/chatgptui/desktop/assets/233364/696ebd93-7a18-44ed-bf3b-9afcae8299cb)

![image](https://github.com/chatgptui/desktop/assets/233364/ec205a6d-7e79-458b-942c-201ad26f8c04)

**Comment by chatgptui** [comment]
Thanks for your feedback. Unfortunately, I am now not interested enough in this project to fix a feature that I personally don't use. If you'd like it fixed, please do it yourself.
