### ISSUE TITLE
Auto scroll to bottom doesn't work on Mac

### ISSUE THREAD

**Issue by naoric** [chatgptui/desktop#9]
Couldn't find related configuration, but it seems like whenever a response is being generated, I have to scroll manually to the bottom of the document to see it. 

Is there a way to keep scrolling to the bottom automatically new content is being added?

**Comment by chatgptui** [comment]
I've changed the code to auto-scroll while the text is being generated in https://github.com/chatgptui/desktop/commit/af68fc6d6bd0f7f1bf49c489ff44aa860fddb7dc (0.42.0, which will be released in about 5 minutes). Tell me if it doesn't work in Mac as I don't have access to Mac right now.
